// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaJ4_k0mBT9OGmlsIuVUoF_vrzvj9xFdM',
    appId: '1:2654101329:web:aed49d1fb09f6e483d3d70',
    messagingSenderId: '2654101329',
    projectId: 'dijipos-efce6',
    authDomain: 'dijipos-efce6.firebaseapp.com',
    storageBucket: 'dijipos-efce6.firebasestorage.app',
    measurementId: 'G-0Q6VFX38J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE8dHYYJbb_bmPA6vrseaXOOPtvpptCjM',
    appId: '1:2654101329:android:fe92f14439f0b18b3d3d70',
    messagingSenderId: '2654101329',
    projectId: 'dijipos-efce6',
    storageBucket: 'dijipos-efce6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfqP1sjN_nZZX438C3d9YPZ8xz9JMVCDE',
    appId: '1:2654101329:ios:414b0fe9af13392e3d3d70',
    messagingSenderId: '2654101329',
    projectId: 'dijipos-efce6',
    storageBucket: 'dijipos-efce6.firebasestorage.app',
    iosBundleId: 'com.example.possystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfqP1sjN_nZZX438C3d9YPZ8xz9JMVCDE',
    appId: '1:2654101329:ios:414b0fe9af13392e3d3d70',
    messagingSenderId: '2654101329',
    projectId: 'dijipos-efce6',
    storageBucket: 'dijipos-efce6.firebasestorage.app',
    iosBundleId: 'com.example.possystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaJ4_k0mBT9OGmlsIuVUoF_vrzvj9xFdM',
    appId: '1:2654101329:web:aed49d1fb09f6e483d3d70',
    messagingSenderId: '2654101329',
    projectId: 'dijipos-efce6',
    authDomain: 'dijipos-efce6.firebaseapp.com',
    storageBucket: 'dijipos-efce6.firebasestorage.app',
    measurementId: 'G-0Q6VFX38J5',
  );

}